- alias: Robyn error
  trigger:
  - platform: state
    entity_id: sensor.vacuum_status
    to: 'error'
  action:
  - service: telegram_bot.send_message
    data_template:
      target: !secret telegram_id_group
      message: 'Robyn hat ein Problem, bitte helft ihm! Vielleicht steckt er fest?'

- alias: Robyn returning home
  trigger:
  - platform: state
    entity_id: sensor.vacuum_status
    from: 'returning'
    to: 'docked'
  action:
  - service: telegram_bot.send_message
    data_template:
      target: !secret telegram_id_group
      message: 'Robyn ist fertig, er hat in {{ states.vacuum.robyn.attributes.cleaning_time }} Minuten {{ states.vacuum.robyn.attributes.cleaned_area }} m² gesaugt!'

- alias: Fabrikator finished
  trigger:
  - platform: state
    entity_id: binary_sensor.octoprint_printing
    to: 'off'
  action:
  - service: telegram_bot.send_photo
    data_template:
      target: !secret telegram_id_nils
      url: 'http://192.168.0.82/webcam/?action=snapshot'
      caption: 'Druck ist fertig!'