- platform: template
  switches:
      robyn_switch:
        friendly_name: Robyn
        entity_id: vacuum.robyn
        value_template: "{{ not is_state('vacuum.robyn', 'docked') }}"
        turn_on:
          service: vacuum.start
          data:
            entity_id: vacuum.robyn
        turn_off:
          service: vacuum.return_to_base
          data:
            entity_id: vacuum.robyn