resources:
  - type: js
    url: /local/kiosk.js
  - type: module
    url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.0.1
  - type: module
    url: /local/simple-thermostat.js?v=1
#  - type: module
#    url: /local/simple-thermostat/simple-thermostat.js?v=1
title: Home
views:
  - id: home
    title: Home
    cards: 
      - type: custom:compact-custom-header
        main_config: true
        menu: overflow
        options: clock
        voice: hide
        clock_format: 12
      - type: vertical-stack
        cards:
          - entity: climate.thermostat_wzs_heat
            type: 'custom:simple-thermostat'
            modes:
              Heat Eco: false
              Manufacturer Specific: false
              Full Power: false
          - entity: climate.thermostat_schlafzimmer_heat
            type: 'custom:simple-thermostat'
            modes:
              Heat Eco: false
              Manufacturer Specific: false
              Full Power: false
          - entity: climate.thermostat_kueche_heat
            type: 'custom:simple-thermostat'
            modes:
              Heat Eco: false
              Manufacturer Specific: false
              Full Power: false
      - type: horizontal-stack
        cards:
          - entity: light.dimmer_esszimmer
            name: Esszimmer
            tap_action:
              action: toggle
            type: entity-button
          - entity: light.dimmer_wohnzimmer
            name: Wohnzimmer
            tap_action:
              action: toggle
            type: entity-button
          - entity: switch.robyn_switch
            icon: 'mdi:robot-vacuum'
            tap-action:
              action: toggle
            type: entity-button
      - type: horizontal-stack    
        cards:
          - entity: light.eule
            icon: 'mdi:owl'
            tap_action:
              action: toggle
            type: entity-button
          - entity: light.dimmer_schlafzimmer_level
            name: Schlafzimmer
            tap_action:
              action: toggle
            type: entity-button
          - entity: light.neopixellight
            name: SZ LED
            tap_action:
              action: toggle
            type: entity-button
      - type: horizontal-stack
        cards:
          - entity: light.stehlampe
            icon: 'mdi:floor-lamp'
            tap_action:
              action: toggle
            type: entity-button
          - entity: light.kaktus
            icon: 'mdi:flower'
            tap_action:
              action: toggle
            type: entity-button
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
            - type: entity-button
              entity: script.wohnzimmer_media_tv
              name: Fernsehen
              icon: 'mdi:television-classic'
              tap_action:
                action: call-service
                service: script.wohnzimmer_media_tv
            - type: entity-button
              entity: script.wohnzimmer_media_radio
              name: Radio
              icon: 'mdi:radio'
              tap_action:
                action: call-service
                service: script.wohnzimmer_media_radio
            - type: entity-button
              entity: script.wohnzimmer_media_tagesschau
              name: Tagesschau
              icon: 'mdi:earth'
              tap_action:
                action: call-service
                service: script.wohnzimmer_media_tagesschau
        - type: horizontal-stack
          cards:
            - type: entity-button
              entity: script.wohnzimmer_media_cast
              name: Cast
              icon: 'mdi:cast'
              tap_action:
                action: call-service
                service: script.wohnzimmer_media_cast
            - type: entity-button
              entity: script.wohnzimmer_media_off
              name: TV aus
              icon: 'mdi:television-off'
              tap_action:
                action: call-service
                service: script.wohnzimmer_media_off
      - type: media-control
        entity:  media_player.chromecast0605
      - type: sensor
        entity: sensor.aussen_temperatur
        graph: line
        detail: 2
